chore(fuzzing): Meet required check expectation
Signed-off-by: Julien Pivotto <291750+roidelapluie@users.noreply.github.com>

diff --git a/.github/workflows/fuzzing.yml b/.github/workflows/fuzzing.yml
--- a/.github/workflows/fuzzing.yml
+++ b/.github/workflows/fuzzing.yml
@@ -1,4 +1,4 @@
-name: Fuzzing
+name: fuzzing
 on:
   workflow_call:
 permissions:
@@ -30,3 +30,18 @@ jobs:
         with:
           name: fuzz-artifacts-${{ matrix.fuzz_test }}
           path: promql/testdata/fuzz/${{ matrix.fuzz_test }}
+  fuzzing_status:
+    # This status check aggregates the individual matrix jobs of the fuzzing
+    # step into a final status. Fails if a single matrix job fails, succeeds if
+    # all matrix jobs succeed.
+    name: Fuzzing
+    runs-on: ubuntu-latest
+    needs: [fuzzing]
+    if: always()
+    steps:
+      - name: Successful fuzzing
+        if: ${{ !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled')) }}
+        run: exit 0
+      - name: Failing or cancelled fuzzing
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
